### ISSUE TITLE
Releasing the re-tuned models?

### ISSUE THREAD

**Issue by vishaal27** [BAAI-DCAI/Visual-Instruction-Tuning#1]
Hi,
Thanks for your impressive efforts on scaling up the visual instruction tuning data, and obtaining qualitatively stronger results in multi-modal conversations. I would like to play around a bit to compare the true effects of the SVIT data compared to the older LLaVA/MiniGPT4 data---are you planning on releasing the re-tuned models on the SVIT data?

**Comment by BoyaWu10** [comment]
Hi @vishaal27, thanks for the interest in this project. Currently we do not have any plans on releasing the fine-tuned models. We just fine-tuned the models to verify the effectiveness of the dataset and we believe that better performance can be achieved if improve the training protocol and carefully tune the hyper-parameters.

**Comment by FuxiaoLiu** [comment]
> Hi,
> Thanks for your impressive efforts on scaling up the visual instruction tuning data, and obtaining qualitatively stronger results in multi-modal conversations. I would like to play around a bit to compare the true effects of the SVIT data compared to the older LLaVA/MiniGPT4 data---are you planning on releasing the re-tuned models on the SVIT data?

Hi @vishaal27 Thanks for your efforts! Have you ever tried finetuning LLaVA on this dataset:

[Mitigating Hallucination in Large Multi-Modal Models via Robust Instruction Tuning](https://arxiv.org/abs/2306.14565)

It has 300k good-quality instruction data. I have ever finetuned minigpt4 and mplug-owl but failed to fine-tune llava.
