### ISSUE TITLE
Code about prompting the GPT-4

### ISSUE THREAD

**Issue by Gary-code** [BAAI-DCAI/Visual-Instruction-Tuning#10]
Will you provide the code about prompting the GPT-4 for instruction data?

**Comment by BoyaWu10** [comment]
Hi @Gary-code, thanks for your interest in this work. Currently we have no plan to release the codes about prompting GPT-4, but we have released the prompts that we use in this [folder](https://github.com/BAAI-DCAI/Visual-Instruction-Tuning/tree/main/prompts). Hope it helps!
