### ISSUE TITLE
images.zip corrupted?

### ISSUE THREAD

**Issue by tonylins** [BAAI-DCAI/Visual-Instruction-Tuning#2]
Hi, thanks for the great work! I downloaded the dataset from the huggingface hub, but got `zipfile corrupt` error when trying to unzip `images.zip`. Is there any idea why it happens? Thanks!

**Comment by tensorboy** [comment]
Identified same issues, the images.zip is corrupted

**Comment by BoyaWu10** [comment]
@tonylins @tensorboy Thanks for the interest in this project. We've updated `images.zip` with the original packages from Visual Genome, which is splitted into two smaller packages `images.zip` and `images2.zip`.

**Comment by BoyaWu10** [comment]
Feel free to reopen it if the issue still exists.
