### ISSUE TITLE
Is there any overlap between svit and llava sft data?

### ISSUE THREAD

**Issue by aprilehannibal** [BAAI-DCAI/Visual-Instruction-Tuning#3]
Great work! I'd like to know is there any overlap between svit and llava_instruct_150k data ? Thanks a lot!

**Comment by BoyaWu10** [comment]
Hi @aprilehannibal, the images of SVIT are from Visual Genome, which is originally sourced from MS-COCO. And the images in llava_instruct_150k are from MS-COCO as well. There may be some overlaps of images between these two datasets, but the instructions and responses are different, as they are generated separately with different prompts.
