### ISSUE TITLE
Some questions about ChatGPT API.

### ISSUE THREAD

**Issue by gray311** [BAAI-DCAI/Visual-Instruction-Tuning#4]
I would like to know what is your speed in generating data using ChatGPT API? (GPT-3.5 and GPT-4) . 
I was generating fast with GPT-3.5 API before in April, but now it's very slow, even though I'm plus user. So would like to know what you guys are doing.

**Comment by BoyaWu10** [comment]
Hi @gray311, our responses are mainly collected in June and we use the GPT-4 Chatbot, which means we send prompts and save responses from the website. We didn't use the APIs. Hope it helps!
